In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#upload raw parking meter transaction data, 'treas_meters_2017_pole_by_mo_day_datasd.csv'
raw_trans = pd.read_csv('../raw_data/treas_meters_2017_pole_by_mo_day_datasd.csv')
raw_trans

        pole_id meter_type  month  day  sum_trans_amt  num_trans
0        1-1004         SS      1    2            390          6
1        1-1004         SS      1    3           1055         14
2        1-1004         SS      1    4            725          7
3        1-1004         SS      1    5           1140          7
4        1-1004         SS      1    6            925          6
5        1-1004         SS      1    7           1184         23
6        1-1004         SS      1    9            345          5
7        1-1004         SS      1   10            500          2
8        1-1004         SS      1   11           1000          5
9        1-1004         SS      1   12            895         11
10       1-1004         SS      1   13            680          7
11       1-1004         SS      1   14           1260         12
12       1-1004         SS      1   17           1375         23
13       1-1004         SS      1   18           1370         12
14       1-1004         SS      1   19           1080         10
15       1-1004         SS      1   20            850         14
16       1-1004         SS      1   21            940          9
17       1-1004         SS      1   23           1105         12
18       1-1004         SS      1   24            905         11
19       1-1004         SS      1   25            425          2
20       1-1004         SS      1   26            175          1
21       1-1004         SS      1   27           1275          8
22       1-1004         SS      1   28           1215          6
23       1-1004         SS      1   30            295          4
24       1-1004         SS      1   31           1195         15
25       1-1004         SS      2    1           1075          5
26       1-1004         SS      2    2           1120          8
27       1-1004         SS      2    3           1400         14
28       1-1004         SS      2    4           1140         10
29       1-1004         SS      2    6           1210         13
...         ...        ...    ...  ...            ...        ...
495487  WUV-119         SS      4   15            700          6
495488  WUV-119         SS      4   17            480          6
495489  WUV-119         SS      4   18           1175         11
495490  WUV-119         SS      4   19            275          3
495491  WUV-119         SS      4   20            650          4
495492  WUV-119         SS      4   21            925          8
495493  WUV-119         SS      4   22            750          4
495494  WUV-119         SS      4   24            545          3
495495  WUV-119         SS      4   25            900          5
495496  WUV-119         SS      4   26            760          6
495497  WUV-119         SS      4   27            625          3
495498  WUV-119         SS      4   28            910         16
495499  WUV-119         SS      5    1            500          3
495500  WUV-119         SS      5    2            875          5
495501  WUV-119         SS      5    3            485          5
495502  WUV-119         SS      5    4            875          5
495503  WUV-119         SS      5    5           1025          5
495504  WUV-119         SS      5    6            500          2
495505  WUV-119         SS      5    8            600          3
495506  WUV-119         SS      5    9            375          2
495507  WUV-119         SS      5   10            505          6
495508  WUV-119         SS      5   11            500          3
495509  WUV-119         SS      5   12            675          4
495510  WUV-119         SS      5   13            850          4
495511  WUV-119         SS      5   15            550          3
495512  WUV-119         SS      5   16            875          5
495513  WUV-119         SS      5   17            725          3
495514  WUV-119         SS      5   18            375          2
495515  WUV-119         SS      5   20            270          4
495516  WUV-119         SS      5   22            570          5

[495517 rows x 6 columns]

In [3]:
#sum of transaction amount based on pole_id
raw_trans['combined_parking_meter_data'] = raw_trans.groupby(['pole_id'])['sum_trans_amt'].transform('sum')
raw_trans

,pole_id,meter_type,month,day,sum_trans_amt,num_trans,combined_parking_meter_data
0,1-1004,SS,1,2,390,6,95394
1,1-1004,SS,1,3,1055,14,95394
2,1-1004,SS,1,4,725,7,95394
3,1-1004,SS,1,5,1140,7,95394
4,1-1004,SS,1,6,925,6,95394
5,1-1004,SS,1,7,1184,23,95394
6,1-1004,SS,1,9,345,5,95394
7,1-1004,SS,1,10,500,2,95394
8,1-1004,SS,1,11,1000,5,95394
9,1-1004,SS,1,12,895,11,95394
10,1-1004,SS,1,13,680,7,95394
11,1-1004,SS,1,14,1260,12,95394
12,1-1004,SS,1,17,1375,23,95394
13,1-1004,SS,1,18,1370,12,95394
14,1-1004,SS,1,19,1080,10,95394
15,1-1004,SS,1,20,850,14,95394
16,1-1004,SS,1,21,940,9,95394
17,1-1004,SS,1,23,1105,12,95394
18,1-1004,SS,1,24,905,11,95394
19,1-1004,SS,1,25,425,2,95394
20,1-1004,SS,1,26,175,1,95394
21,1-1004,SS,1,27,1275,8,95394
22,1-1004,SS,1,28,1215,6,95394
23,1-1004,SS,1,30,295,4,95394
24,1-1004,SS,1,31,1195,15,95394
25,1-1004,SS,2,1,1075,5,95394
26,1-1004,SS,2,2,1120,8,95394
27,1-1004,SS,2,3,1400,14,95394
28,1-1004,SS,2,4,1140,10,95394
29,1-1004,SS,2,6,1210,13,95394
...,...,...,...,...,...,...,...
495487,WUV-119,SS,4,15,700,6,62127
495488,WUV-119,SS,4,17,480,6,62127
495489,WUV-119,SS,4,18,1175,11,62127
495490,WUV-119,SS,4,19,275,3,62127
495491,WUV-119,SS,4,20,650,4,62127
495492,WUV-119,SS,4,21,925,8,62127
495493,WUV-119,SS,4,22,750,4,62127
495494,WUV-119,SS,4,24,545,3,62127
495495,WUV-119,SS,4,25,900,5,62127
495496,WUV-119,SS,4,26,760,6,62127
495497,WUV-119,SS,4,27,625,3,62127
495498,WUV-119,SS,4,28,910,16,62127
495499,WUV-119,SS,5,1,500,3,62127
495500,WUV-119,SS,5,2,875,5,62127
495501,WUV-119,SS,5,3,485,5,62127
495502,WUV-119,SS,5,4,875,5,62127
495503,WUV-119,SS,5,5,1025,5,62127
495504,WUV-119,SS,5,6,500,2,62127
495505,WUV-119,SS,5,8,600,3,62127
495506,WUV-119,SS,5,9,375,2,62127
495507,WUV-119,SS,5,10,505,6,62127
495508,WUV-119,SS,5,11,500,3,62127
495509,WUV-119,SS,5,12,675,4,62127
495510,WUV-119,SS,5,13,850,4,62127
495511,WUV-119,SS,5,15,550,3,62127
495512,WUV-119,SS,5,16,875,5,62127
495513,WUV-119,SS,5,17,725,3,62127
495514,WUV-119,SS,5,18,375,2,62127
495515,WUV-119,SS,5,20,270,4,62127
495516,WUV-119,SS,5,22,570,5,62127

In [4]:
#drop columns 'meter_type', 'month', 'day', 'num_trans'
clean_trans = raw_trans.drop(['meter_type', 'month', 'day', 'num_trans'],axis = 1)
clean_trans

        pole_id  sum_trans_amt  combined_parking_meter_data
0        1-1004            390                        95394
1        1-1004           1055                        95394
2        1-1004            725                        95394
3        1-1004           1140                        95394
4        1-1004            925                        95394
5        1-1004           1184                        95394
6        1-1004            345                        95394
7        1-1004            500                        95394
8        1-1004           1000                        95394
9        1-1004            895                        95394
10       1-1004            680                        95394
11       1-1004           1260                        95394
12       1-1004           1375                        95394
13       1-1004           1370                        95394
14       1-1004           1080                        95394
15       1-1004            850                        95394
16       1-1004            940                        95394
17       1-1004           1105                        95394
18       1-1004            905                        95394
19       1-1004            425                        95394
20       1-1004            175                        95394
21       1-1004           1275                        95394
22       1-1004           1215                        95394
23       1-1004            295                        95394
24       1-1004           1195                        95394
25       1-1004           1075                        95394
26       1-1004           1120                        95394
27       1-1004           1400                        95394
28       1-1004           1140                        95394
29       1-1004           1210                        95394
...         ...            ...                          ...
495487  WUV-119            700                        62127
495488  WUV-119            480                        62127
495489  WUV-119           1175                        62127
495490  WUV-119            275                        62127
495491  WUV-119            650                        62127
495492  WUV-119            925                        62127
495493  WUV-119            750                        62127
495494  WUV-119            545                        62127
495495  WUV-119            900                        62127
495496  WUV-119            760                        62127
495497  WUV-119            625                        62127
495498  WUV-119            910                        62127
495499  WUV-119            500                        62127
495500  WUV-119            875                        62127
495501  WUV-119            485                        62127
495502  WUV-119            875                        62127
495503  WUV-119           1025                        62127
495504  WUV-119            500                        62127
495505  WUV-119            600                        62127
495506  WUV-119            375                        62127
495507  WUV-119            505                        62127
495508  WUV-119            500                        62127
495509  WUV-119            675                        62127
495510  WUV-119            850                        62127
495511  WUV-119            550                        62127
495512  WUV-119            875                        62127
495513  WUV-119            725                        62127
495514  WUV-119            375                        62127
495515  WUV-119            270                        62127
495516  WUV-119            570                        62127

[495517 rows x 3 columns]

In [5]:
#eliminated duplicate sum value for each pole_id
clean_trans = clean_trans.drop_duplicates(subset=['pole_id'], keep='first')
clean_trans

        pole_id  sum_trans_amt  combined_parking_meter_data
0        1-1004            390                        95394
114      1-1006            205                       100581
227      1-1008            405                        98064
340      1-1020            230                        39725
453      1-1310             50                        96666
569      1-1312            325                        94493
684      1-1313            940                        91660
797      1-1314            360                        96900
912      1-1315            250                        89538
1027     1-1317             55                        86209
1138     1-1400            150                        87558
1253     1-1402            970                        87443
1366     1-1410            145                        72603
1482     1-1412            935                        73041
1592     1-1420            125                        80272
1706     1-1424            145                        76364
1818     1-1500            250                        77145
1931     1-1502            625                        69223
2043     1-1504            375                        69374
2155     1-1506              5                        62829
2266     1-1508            100                        59605
2376     1-1510            225                        52637
2486     1-1512            375                        55611
2598     1-1514            525                        50841
2708     1-1516            225                        45219
2814     1-1518            500                        54207
2926     1-1524            125                        48233
3034     1-1526            155                        45420
3138     1-2001            465                        77025
3245     1-2005             80                        75618
...         ...            ...                          ...
492229   WT-303            100                        32395
492323   WT-305            685                        34453
492416   WT-307            500                        39728
492511   WT-309            360                        49793
492617   WT-310            390                        55893
492727   WT-321            210                        49214
492836   WT-322            300                        62495
492945   WT-323            490                        48883
493052   WT-324            470                        54330
493158   WT-327            285                        44649
493269   WT-329            640                        58662
493380   WT-333              5                        51857
493492   WT-336            250                        61369
493606   WT-338            125                        57287
493715   WT-340            750                        58861
493823   WT-400            425                        79350
493938   WT-402            415                        49268
494040   WT-406            425                        80983
494156   WT-408            280                        78377
494269   WT-410            375                        80767
494381   WT-412            325                        87066
494497   WT-414            675                        77047
494605  WUV-111            150                        77929
494719  WUV-113            385                        63256
494835  WUV-114            200                        52234
494947  WUV-115            415                        63335
495063  WUV-116            200                        56179
495177  WUV-117            395                        58672
495291  WUV-118             45                        74653
495407  WUV-119            725                        62127

[4710 rows x 3 columns]

In [6]:
#export to new, clean data to csv file 'clean_combined_parking_meter_data'
clean_trans.to_csv('../clean_data/clean_combined_parking_meter_data.csv')
clean_trans

        pole_id  sum_trans_amt  combined_parking_meter_data
0        1-1004            390                        95394
114      1-1006            205                       100581
227      1-1008            405                        98064
340      1-1020            230                        39725
453      1-1310             50                        96666
569      1-1312            325                        94493
684      1-1313            940                        91660
797      1-1314            360                        96900
912      1-1315            250                        89538
1027     1-1317             55                        86209
1138     1-1400            150                        87558
1253     1-1402            970                        87443
1366     1-1410            145                        72603
1482     1-1412            935                        73041
1592     1-1420            125                        80272
1706     1-1424            145                        76364
1818     1-1500            250                        77145
1931     1-1502            625                        69223
2043     1-1504            375                        69374
2155     1-1506              5                        62829
2266     1-1508            100                        59605
2376     1-1510            225                        52637
2486     1-1512            375                        55611
2598     1-1514            525                        50841
2708     1-1516            225                        45219
2814     1-1518            500                        54207
2926     1-1524            125                        48233
3034     1-1526            155                        45420
3138     1-2001            465                        77025
3245     1-2005             80                        75618
...         ...            ...                          ...
492229   WT-303            100                        32395
492323   WT-305            685                        34453
492416   WT-307            500                        39728
492511   WT-309            360                        49793
492617   WT-310            390                        55893
492727   WT-321            210                        49214
492836   WT-322            300                        62495
492945   WT-323            490                        48883
493052   WT-324            470                        54330
493158   WT-327            285                        44649
493269   WT-329            640                        58662
493380   WT-333              5                        51857
493492   WT-336            250                        61369
493606   WT-338            125                        57287
493715   WT-340            750                        58861
493823   WT-400            425                        79350
493938   WT-402            415                        49268
494040   WT-406            425                        80983
494156   WT-408            280                        78377
494269   WT-410            375                        80767
494381   WT-412            325                        87066
494497   WT-414            675                        77047
494605  WUV-111            150                        77929
494719  WUV-113            385                        63256
494835  WUV-114            200                        52234
494947  WUV-115            415                        63335
495063  WUV-116            200                        56179
495177  WUV-117            395                        58672
495291  WUV-118             45                        74653
495407  WUV-119            725                        62127

[4710 rows x 3 columns]

In [11]:
#import cleaned parking meter location data file
clean_parking_loc = pd.read_csv('../clean_data/parking_meter_location.csv')
clean_parking_loc

      Unnamed: 0     pole   longitude   latitude
0              0  CC-1003 -117.145178  32.700353
1              1  CC-1005 -117.145178  32.700352
2              2  CC-1011 -117.145349  32.700155
3              3  CC-1013 -117.145405  32.700107
4              4  CC-1015 -117.145539  32.699987
5              5  CC-1017 -117.145540  32.699985
6              6  CC-1019 -117.145545  32.699981
7              7  CC-1103 -117.145973  32.699544
8              8  CC-1105 -117.145973  32.699545
9              9  CC-1107 -117.146065  32.699490
10            10  CC-1109 -117.146065  32.699491
11            11  CC-1111 -117.145915  32.699629
12            12  CC-1115 -117.145978  32.699501
13            13  CC-1117 -117.146053  32.699556
14            14  MN-1827 -117.147804  32.699751
15            15  MN-1829 -117.147282  32.699391
16            16  MN-2808 -117.133469  32.692883
17            17  MN-2812 -117.133316  32.692886
18            18  MN-2814 -117.133124  32.692890
19            19  MN-2816 -117.132968  32.692891
20            20  MN-2824 -117.132815  32.692891
21            21  MN-2826 -117.132661  32.692892
22            22  MN-2828 -117.132508  32.692892
23            23  MN-2830 -117.132354  32.692892
24            24  MN-2838 -117.132162  32.692892
25            25  MN-2840 -117.132009  32.692892
26            26  MN-2842 -117.131855  32.692893
27            27  NL-1701 -117.148149  32.702693
28            28  NL-1703 -117.147903  32.702524
29            29  NL-1711 -117.147627  32.702333
...          ...      ...         ...        ...
4901        4901       --    0.000000   0.000000
4902        4902       --    0.000000   0.000000
4903        4903       --    0.000000   0.000000
4904        4904       --    0.000000   0.000000
4905        4905       --    0.000000   0.000000
4906        4906       --    0.000000   0.000000
4907        4907       --    0.000000   0.000000
4908        4908       --    0.000000   0.000000
4909        4909       --    0.000000   0.000000
4910        4910       --    0.000000   0.000000
4911        4911       --    0.000000   0.000000
4912        4912       --    0.000000   0.000000
4913        4913       --    0.000000   0.000000
4914        4914       --    0.000000   0.000000
4915        4915       --    0.000000   0.000000
4916        4916       --    0.000000   0.000000
4917        4917       --    0.000000   0.000000
4918        4918       --    0.000000   0.000000
4919        4919       --    0.000000   0.000000
4920        4920       --    0.000000   0.000000
4921        4921       --    0.000000   0.000000
4922        4922       --    0.000000   0.000000
4923        4923       --    0.000000   0.000000
4924        4924       --    0.000000   0.000000
4925        4925       --    0.000000   0.000000
4926        4926       --    0.000000   0.000000
4927        4927       --    0.000000   0.000000
4928        4928       --    0.000000   0.000000
4929        4929       --    0.000000   0.000000
4930        4930       --    0.000000   0.000000

[4931 rows x 4 columns]

In [12]:
#drop rows with zero longitude and latitudes 
clean_parking_loc = clean_parking_loc.drop(clean_parking_loc[clean_parking_loc.longitude==0.000000].index)
clean_parking_loc

      Unnamed: 0     pole   longitude   latitude
0              0  CC-1003 -117.145178  32.700353
1              1  CC-1005 -117.145178  32.700352
2              2  CC-1011 -117.145349  32.700155
3              3  CC-1013 -117.145405  32.700107
4              4  CC-1015 -117.145539  32.699987
5              5  CC-1017 -117.145540  32.699985
6              6  CC-1019 -117.145545  32.699981
7              7  CC-1103 -117.145973  32.699544
8              8  CC-1105 -117.145973  32.699545
9              9  CC-1107 -117.146065  32.699490
10            10  CC-1109 -117.146065  32.699491
11            11  CC-1111 -117.145915  32.699629
12            12  CC-1115 -117.145978  32.699501
13            13  CC-1117 -117.146053  32.699556
14            14  MN-1827 -117.147804  32.699751
15            15  MN-1829 -117.147282  32.699391
16            16  MN-2808 -117.133469  32.692883
17            17  MN-2812 -117.133316  32.692886
18            18  MN-2814 -117.133124  32.692890
19            19  MN-2816 -117.132968  32.692891
20            20  MN-2824 -117.132815  32.692891
21            21  MN-2826 -117.132661  32.692892
22            22  MN-2828 -117.132508  32.692892
23            23  MN-2830 -117.132354  32.692892
24            24  MN-2838 -117.132162  32.692892
25            25  MN-2840 -117.132009  32.692892
26            26  MN-2842 -117.131855  32.692893
27            27  NL-1701 -117.148149  32.702693
28            28  NL-1703 -117.147903  32.702524
29            29  NL-1711 -117.147627  32.702333
...          ...      ...         ...        ...
4638        4638   WN-911 -117.155391  32.750307
4639        4639   WN-913 -117.155341  32.750315
4640        4640   WN-915 -117.155300  32.750320
4641        4641  MO-1729 -117.146760  32.759032
4642        4642  MO-1732 -117.146550  32.759207
4643        4643  MO-1734 -117.146514  32.759195
4644        4644  MO-1737 -117.146457  32.759051
4645        4645  PB-4405 -117.146154  32.757706
4646        4646  PB-4407 -117.146170  32.757771
4647        4647  PB-4409 -117.146247  32.757697
4648        4648  PB-4411 -117.146033  32.757840
4649        4649  PB-4428 -117.146303  32.758444
4650        4650  PB-4430 -117.146333  32.758516
4651        4651  PB-4432 -117.146348  32.758603
4652        4652  PB-4434 -117.146337  32.758677
4653        4653  PB-4436 -117.146344  32.758751
4654        4654  PB-4442 -117.146366  32.758907
4655        4655  PB-4444 -117.146343  32.758930
4656        4656  PB-4501 -117.146293  32.759215
4657        4657  PB-4503 -117.146182  32.759404
4658        4658  PB-4542 -117.146364  32.760823
4659        4659  PB-4544 -117.146381  32.760837
4660        4660  PB-4612 -117.146240  32.761347
4661        4661  PB-4614 -117.146381  32.761526
4662        4662  PB-4616 -117.146246  32.761377
4663        4663  PB-4618 -117.146344  32.761601
4664        4664  PB-4622 -117.146241  32.761375
4665        4665  PB-4631 -117.146185  32.762074
4666        4666  PB-4633 -117.146180  32.762115
4667        4667  PB-4635 -117.146182  32.762184

[4668 rows x 4 columns]

In [13]:
#rename pole column header of clean_parking_loc data to 'pole_id' to match the header of the clean_combined_parking_meter_data dataset
clean_parking_loc.columns= ['index', 'pole_id', 'longitude', 'latitude']
clean_parking_loc

      index  pole_id   longitude   latitude
0         0  CC-1003 -117.145178  32.700353
1         1  CC-1005 -117.145178  32.700352
2         2  CC-1011 -117.145349  32.700155
3         3  CC-1013 -117.145405  32.700107
4         4  CC-1015 -117.145539  32.699987
5         5  CC-1017 -117.145540  32.699985
6         6  CC-1019 -117.145545  32.699981
7         7  CC-1103 -117.145973  32.699544
8         8  CC-1105 -117.145973  32.699545
9         9  CC-1107 -117.146065  32.699490
10       10  CC-1109 -117.146065  32.699491
11       11  CC-1111 -117.145915  32.699629
12       12  CC-1115 -117.145978  32.699501
13       13  CC-1117 -117.146053  32.699556
14       14  MN-1827 -117.147804  32.699751
15       15  MN-1829 -117.147282  32.699391
16       16  MN-2808 -117.133469  32.692883
17       17  MN-2812 -117.133316  32.692886
18       18  MN-2814 -117.133124  32.692890
19       19  MN-2816 -117.132968  32.692891
20       20  MN-2824 -117.132815  32.692891
21       21  MN-2826 -117.132661  32.692892
22       22  MN-2828 -117.132508  32.692892
23       23  MN-2830 -117.132354  32.692892
24       24  MN-2838 -117.132162  32.692892
25       25  MN-2840 -117.132009  32.692892
26       26  MN-2842 -117.131855  32.692893
27       27  NL-1701 -117.148149  32.702693
28       28  NL-1703 -117.147903  32.702524
29       29  NL-1711 -117.147627  32.702333
...     ...      ...         ...        ...
4638   4638   WN-911 -117.155391  32.750307
4639   4639   WN-913 -117.155341  32.750315
4640   4640   WN-915 -117.155300  32.750320
4641   4641  MO-1729 -117.146760  32.759032
4642   4642  MO-1732 -117.146550  32.759207
4643   4643  MO-1734 -117.146514  32.759195
4644   4644  MO-1737 -117.146457  32.759051
4645   4645  PB-4405 -117.146154  32.757706
4646   4646  PB-4407 -117.146170  32.757771
4647   4647  PB-4409 -117.146247  32.757697
4648   4648  PB-4411 -117.146033  32.757840
4649   4649  PB-4428 -117.146303  32.758444
4650   4650  PB-4430 -117.146333  32.758516
4651   4651  PB-4432 -117.146348  32.758603
4652   4652  PB-4434 -117.146337  32.758677
4653   4653  PB-4436 -117.146344  32.758751
4654   4654  PB-4442 -117.146366  32.758907
4655   4655  PB-4444 -117.146343  32.758930
4656   4656  PB-4501 -117.146293  32.759215
4657   4657  PB-4503 -117.146182  32.759404
4658   4658  PB-4542 -117.146364  32.760823
4659   4659  PB-4544 -117.146381  32.760837
4660   4660  PB-4612 -117.146240  32.761347
4661   4661  PB-4614 -117.146381  32.761526
4662   4662  PB-4616 -117.146246  32.761377
4663   4663  PB-4618 -117.146344  32.761601
4664   4664  PB-4622 -117.146241  32.761375
4665   4665  PB-4631 -117.146185  32.762074
4666   4666  PB-4633 -117.146180  32.762115
4667   4667  PB-4635 -117.146182  32.762184

[4668 rows x 4 columns]

In [14]:
#drop index column
clean_parking_loc = clean_parking_loc.drop(['index'], axis = 1)
clean_parking_loc

      pole_id   longitude   latitude
0     CC-1003 -117.145178  32.700353
1     CC-1005 -117.145178  32.700352
2     CC-1011 -117.145349  32.700155
3     CC-1013 -117.145405  32.700107
4     CC-1015 -117.145539  32.699987
5     CC-1017 -117.145540  32.699985
6     CC-1019 -117.145545  32.699981
7     CC-1103 -117.145973  32.699544
8     CC-1105 -117.145973  32.699545
9     CC-1107 -117.146065  32.699490
10    CC-1109 -117.146065  32.699491
11    CC-1111 -117.145915  32.699629
12    CC-1115 -117.145978  32.699501
13    CC-1117 -117.146053  32.699556
14    MN-1827 -117.147804  32.699751
15    MN-1829 -117.147282  32.699391
16    MN-2808 -117.133469  32.692883
17    MN-2812 -117.133316  32.692886
18    MN-2814 -117.133124  32.692890
19    MN-2816 -117.132968  32.692891
20    MN-2824 -117.132815  32.692891
21    MN-2826 -117.132661  32.692892
22    MN-2828 -117.132508  32.692892
23    MN-2830 -117.132354  32.692892
24    MN-2838 -117.132162  32.692892
25    MN-2840 -117.132009  32.692892
26    MN-2842 -117.131855  32.692893
27    NL-1701 -117.148149  32.702693
28    NL-1703 -117.147903  32.702524
29    NL-1711 -117.147627  32.702333
...       ...         ...        ...
4638   WN-911 -117.155391  32.750307
4639   WN-913 -117.155341  32.750315
4640   WN-915 -117.155300  32.750320
4641  MO-1729 -117.146760  32.759032
4642  MO-1732 -117.146550  32.759207
4643  MO-1734 -117.146514  32.759195
4644  MO-1737 -117.146457  32.759051
4645  PB-4405 -117.146154  32.757706
4646  PB-4407 -117.146170  32.757771
4647  PB-4409 -117.146247  32.757697
4648  PB-4411 -117.146033  32.757840
4649  PB-4428 -117.146303  32.758444
4650  PB-4430 -117.146333  32.758516
4651  PB-4432 -117.146348  32.758603
4652  PB-4434 -117.146337  32.758677
4653  PB-4436 -117.146344  32.758751
4654  PB-4442 -117.146366  32.758907
4655  PB-4444 -117.146343  32.758930
4656  PB-4501 -117.146293  32.759215
4657  PB-4503 -117.146182  32.759404
4658  PB-4542 -117.146364  32.760823
4659  PB-4544 -117.146381  32.760837
4660  PB-4612 -117.146240  32.761347
4661  PB-4614 -117.146381  32.761526
4662  PB-4616 -117.146246  32.761377
4663  PB-4618 -117.146344  32.761601
4664  PB-4622 -117.146241  32.761375
4665  PB-4631 -117.146185  32.762074
4666  PB-4633 -117.146180  32.762115
4667  PB-4635 -117.146182  32.762184

[4668 rows x 3 columns]

In [15]:
#merge datasets based on matching parking meter IDs
merged_id = pd.merge(clean_parking_loc, clean_trans, on='pole_id')
merged_id

,pole_id,longitude,latitude,sum_trans_amt,combined_parking_meter_data
0,CC-1003,-117.145178,32.700353,85,27724
1,CC-1005,-117.145178,32.700352,250,31869
2,CC-1011,-117.145349,32.700155,515,57232
3,CC-1013,-117.145405,32.700107,345,37887
4,CC-1015,-117.145539,32.699987,390,25950
5,CC-1017,-117.145540,32.699985,50,30021
6,CC-1019,-117.145545,32.699981,70,30962
7,CC-1103,-117.145973,32.699544,110,47437
8,CC-1105,-117.145973,32.699545,360,49463
9,CC-1107,-117.146065,32.699490,425,45072
10,CC-1109,-117.146065,32.699491,410,56784
11,CC-1111,-117.145915,32.699629,365,59138
12,CC-1115,-117.145978,32.699501,225,71846
13,CC-1117,-117.146053,32.699556,410,74245
14,MN-1827,-117.147804,32.699751,500,58543
15,MN-1829,-117.147282,32.699391,150,56349
16,MN-2808,-117.133469,32.692883,75,20113
17,MN-2812,-117.133316,32.692886,275,22410
18,MN-2814,-117.133124,32.692890,570,19298
19,MN-2816,-117.132968,32.692891,275,20074
20,MN-2824,-117.132815,32.692891,80,27280
21,MN-2826,-117.132661,32.692892,215,15360
22,MN-2828,-117.132508,32.692892,80,12275
23,MN-2830,-117.132354,32.692892,190,11099
24,MN-2838,-117.132162,32.692892,215,10228
25,MN-2840,-117.132009,32.692892,20,5710
26,MN-2842,-117.131855,32.692893,75,6435
27,NL-1701,-117.148149,32.702693,250,47846
28,NL-1703,-117.147903,32.702524,100,52964
29,NL-1711,-117.147627,32.702333,265,36093
...,...,...,...,...,...
4636,WN-911,-117.155391,32.750307,160,63910
4637,WN-913,-117.155341,32.750315,125,54121
4638,WN-915,-117.155300,32.750320,450,53614
4639,MO-1729,-117.146760,32.759032,780,48935
4640,MO-1732,-117.146550,32.759207,885,55742
4641,MO-1734,-117.146514,32.759195,515,65647
4642,MO-1737,-117.146457,32.759051,390,55188
4643,PB-4405,-117.146154,32.757706,500,42180
4644,PB-4407,-117.146170,32.757771,375,46768
4645,PB-4409,-117.146247,32.757697,590,51318
4646,PB-4411,-117.146033,32.757840,600,64028
4647,PB-4428,-117.146303,32.758444,650,62369
4648,PB-4430,-117.146333,32.758516,850,66383
4649,PB-4432,-117.146348,32.758603,305,63843
4650,PB-4434,-117.146337,32.758677,880,60362
4651,PB-4436,-117.146344,32.758751,475,69988
4652,PB-4442,-117.146366,32.758907,170,34745
4653,PB-4444,-117.146343,32.758930,195,25440
4654,PB-4501,-117.146293,32.759215,520,68792
4655,PB-4503,-117.146182,32.759404,40,76056
4656,PB-4542,-117.146364,32.760823,300,84812
4657,PB-4544,-117.146381,32.760837,655,80511
4658,PB-4612,-117.146240,32.761347,810,94504
4659,PB-4614,-117.146381,32.761526,930,86145
4660,PB-4616,-117.146246,32.761377,625,82591
4661,PB-4618,-117.146344,32.761601,850,93687
4662,PB-4622,-117.146241,32.761375,475,96623
4663,PB-4631,-117.146185,32.762074,909,88122
4664,PB-4633,-117.146180,32.762115,340,89948
4665,PB-4635,-117.146182,32.762184,1165,88053

In [22]:
#export to new, clean data to csv file 'merged_parking_meters.csv'
merged_id.to_csv('../clean_data/merged_parking_meters.csv')

In [17]:
open_pot = pd.read_csv('../clean_data/cleaned_get_it_done_open_potholes.csv')
bus_stops = pd.read_csv('../clean_data/clean_bus_stops.csv')

open_pot

,Unnamed: 0,status_description,mobile_web_status,duplicate_verified,override_duplicate,requested_datetime,closed_date,open,closed,service_name,coordinates,lat,long,sap_problem_type
0,1,Acknowledged,In process,0,0,2017-05-23T18:06:00,NaN,1,0,Pothole,32.79153673521502-117.1544678834988,32.791537,-117.154468,Pothole
1,54,New,New,0,0,2017-05-23T15:31:00,NaN,1,0,Pothole,32.724165-117.05552499999999,32.724165,-117.055525,Pothole
2,60,Acknowledged,In process,0,0,2017-05-23T15:25:00,NaN,1,0,Pothole,32.79042917715904-117.24192641030152,32.790429,-117.241926,Pothole
3,78,Acknowledged,In process,0,0,2017-05-23T14:43:00,NaN,1,0,Pothole,32.760451-117.064381,32.760451,-117.064381,Pothole
4,81,New,New,0,0,2017-05-23T14:40:00,NaN,1,0,Pothole,32.758759-117.063192,32.758759,-117.063192,Pothole
5,88,Acknowledged,In process,0,0,2017-05-23T14:17:00,NaN,1,0,Pothole,32.748611-117.079278,32.748611,-117.079278,Pothole
6,116,Acknowledged,In process,0,1,2017-05-23T12:52:00,NaN,1,0,Pothole,32.844727311545895-117.2670286848815,32.844727,-117.267029,Pothole
7,121,Acknowledged,In process,0,0,2017-05-23T12:45:00,NaN,1,0,Pothole,32.74642288029995-117.1482656743188,32.746423,-117.148266,Pothole
8,125,Acknowledged,In process,0,1,2017-05-23T12:42:00,NaN,1,0,Pothole,32.74642295486662-117.1493714079478,32.746423,-117.149371,Pothole
9,127,Acknowledged,In process,0,0,2017-05-23T12:38:00,NaN,1,0,Pothole,32.74513698504784-117.1605940669536,32.745137,-117.160594,Pothole
10,129,Acknowledged,In process,0,1,2017-05-23T12:35:00,NaN,1,0,Pothole,32.74389887231658-117.1675025952208,32.743899,-117.167503,Pothole
11,132,Acknowledged,In process,0,0,2017-05-23T12:33:00,NaN,1,0,Pothole,32.74431046567182-117.1675273218352,32.744310,-117.167527,Pothole
12,162,Acknowledged,In process,0,0,2017-05-23T11:29:00,NaN,1,0,Pothole,32.69444243838484-117.08357930778253,32.694442,-117.083579,Pothole
13,171,Acknowledged,In process,0,0,2017-05-23T11:18:00,NaN,1,0,Pothole,32.80686925796851-117.1720126672696,32.806869,-117.172013,Pothole
14,177,Acknowledged,In process,0,1,2017-05-23T11:10:00,NaN,1,0,Pothole,32.934440275431015-117.06675191864286,32.934440,-117.066752,Pothole
15,184,Acknowledged,In process,0,0,2017-05-23T10:53:00,NaN,1,0,Pothole,32.73337076775489-117.11800270706021,32.733371,-117.118003,Pothole
16,189,Acknowledged,In process,0,1,2017-05-23T10:44:00,NaN,1,0,Pothole,32.89418388161146-117.2164741159577,32.894184,-117.216474,Pothole
17,271,Acknowledged,In process,0,1,2017-05-23T08:24:00,NaN,1,0,Pothole,32.72718925683984-117.16665153122693,32.727189,-117.166652,Pothole
18,287,Acknowledged,In process,0,1,2017-05-23T07:58:00,NaN,1,0,Pothole,32.912833-117.14364,32.912833,-117.143640,Pothole
19,290,Acknowledged,In process,0,1,2017-05-23T07:46:00,NaN,1,0,Pothole,32.755209-117.10081,32.755209,-117.100810,Pothole
20,365,Acknowledged,In process,0,0,2017-05-23T00:22:00,NaN,1,0,Pothole,33.012889-117.074083,33.012889,-117.074083,Pothole
21,391,Acknowledged,In process,0,0,2017-05-22T21:13:00,NaN,1,0,Pothole,32.7138935-117.13526690000003,32.713893,-117.135267,Pothole
22,405,Acknowledged,In process,0,0,2017-05-22T20:06:00,NaN,1,0,Pothole,32.84046659999999-117.27073471097572,32.840467,-117.270735,Pothole
23,421,Acknowledged,In process,0,0,2017-05-22T19:20:00,NaN,1,0,Pothole,32.702815-117.114701,32.702815,-117.114701,Pothole
24,424,Acknowledged,In process,0,0,2017-05-22T19:14:00,NaN,1,0,Pothole,32.84302652816553-117.2703498882402,32.843027,-117.270350,Pothole
25,433,Acknowledged,In process,0,1,2017-05-22T19:04:00,NaN,1,0,Pothole,33.00544124099706-117.0768245683211,33.005441,-117.076825,Pothole
26,436,Acknowledged,In process,0,0,2017-05-22T18:53:00,NaN,1,0,Other,32.74953741232278-117.098696546027,32.749537,-117.098697,Pothole
27,450,Acknowledged,In process,0,0,2017-05-22T18:27:00,NaN,1,0,Pothole,32.74789-117.237303,32.747890,-117.237303,Pothole
28,553,Acknowledged,In process,0,0,2017-05-22T15:16:00,NaN,1,0,Pothole,32.81522513835952-117.2415051610369,32.815225,-117.241505,Pothole
29,578,Acknowledged,In process,0,0,2017-05-22T14:43:00,NaN,1,0,Pothole,32.72557041848898-117.15054092254638,32.725570,-117.150541,Pothole
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544,63080,Assigned,In process,0,0,2016-12-07T13:29:00,NaN,1,0,Pothole,32.79485630118648-117.0283725730896,32.794856,-117.028373,Pothole
2545,63316,Assigned,In process,0,0,2016-12-06T15:32:00,NaN,1,0,Pothole,32.9367351993692-117.11053399963379,32.936735,-117.110534,Pothole
2546,64295,Assigned,In process,0,0,2016-12-02T09:28:00,NaN,1,0,Pothole,32.7191789-117.234714,32.719179,-117.234714,Pothole
2547,64520,Assigned,In process,0,0,2016-12-01T10:01:00,NaN,1,0,Pothole,32.764591-117.119835,32.764591,-117.119835,Pothole
2548,65147,Assigned,In process,0,0,2016-11-28T16:19:00,NaN,1,0,Pothole,32.83300254019885-117.15486136878656,32.833003,-117.154861,Pothole
2549,65154,Assigned,In process,0,0,2016-11-28T16:08:00,NaN,1,0,Pothole,32.8267594-117.1542287,32.826759,-117.154229,Pothole
2550,65539,Assigned,In process,0,0,2016-11-26T12:53:00,NaN,1,0,Pothole,32.93500173840014-117.0886840392995,32.935002,-117.088684,Pothole
2551,66330,Assigned,In process,0,0,2016-11-21T08:19:00,NaN,1,0,Pothole,32.756955-117.122217,32.756955,-117.122217,Pothole
2552,66822,Assigned,In process,0,0,2016-11-18T10:25:00,NaN,1,0,Pothole,32.832583048650555-117.16385631484985,32.832583,-117.163856,Pothole
2553,67165,Assigned,In process,0,0,2016-11-16T15:21:00,NaN,1,0,Pothole,32.84492887236611-117.26726536109925,32.844929,-117.267265,Pothole
2554,67186,Assigned,In process,0,0,2016-11-16T14:17:00,NaN,1,0,Pothole,32.792961-117.094348,32.792961,-117.094348,Pothole
2555,69840,Assigned,In process,0,0,2016-11-04T09:44:00,NaN,1,0,Pothole,32.8550899-117.2555848,32.855090,-117.255585,Pothole
2556,70921,Assigned,In process,0,0,2016-10-30T10:50:00,NaN,1,0,Pothole,32.76452364728704-117.098880125209,32.764524,-117.098880,Pothole
2557,71891,Assigned,In process,0,1,2016-10-25T12:28:00,NaN,1,0,Pothole,32.74447315605053-117.0535387034224,32.744473,-117.053539,Pothole
2558,72478,Assigned,In process,0,0,2016-10-21T17:31:00,NaN,1,0,Pothole,32.74137309698125-117.25163313491822,32.741373,-117.251633,Pothole
2559,73676,Assigned,In process,0,0,2016-10-14T19:56:00,NaN,1,0,Pothole,32.75590449771817-117.22239284439081,32.755904,-117.222393,Pothole
2560,73685,Assigned,In process,0,0,2016-10-14T19:16:00,NaN,1,0,Pothole,32.7589748-117.1104124,32.758975,-117.110412,Pothole
2561,74205,Assigned,In process,0,0,2016-10-12T10:44:00,NaN,1,0,Pothole,32.91068546333224-117.1551517839332,32.910685,-117.155152,Pothole
2562,76245,Acknowledged,In process,1,1,2016-10-01T14:55:00,NaN,1,0,Pothole,32.78012843709192-117.1330131849759,32.780128,-117.133013,Pothole
2563,76258,Assigned,In process,0,1,2016-10-01T12:40:00,NaN,1,0,Pothole,32.740168-117.109509,32.740168,-117.109509,Pothole
2564,77885,Assigned,In process,0,1,2016-09-23T13:53:00,NaN,1,0,Pothole,32.815382-117.153928,32.815382,-117.153928,Pothole
2565,78187,Acknowledged,In process,1,1,2016-09-22T08:43:00,NaN,1,0,Pothole,32.828322-117.087653,32.828322,-117.087653,Pothole
2566,79147,Acknowledged,In process,1,1,2016-09-18T08:19:00,NaN,1,0,Pothole,32.780388-117.132709,32.780388,-117.132709,Pothole
2567,83117,Assigned,In process,0,0,2016-08-29T00:34:00,NaN,1,0,Pothole,32.75530034386429-117.13513271091071,32.755300,-117.135133,Pothole
2568,85987,Assigned,In process,0,0,2016-08-12T09:53:00,NaN,1,0,Pothole,32.9152215-117.14266,32.915222,-117.142660,Pothole
2569,91511,Assigned,In process,0,0,2016-07-13T17:47:00,NaN,1,0,Pothole,32.84698291219105-117.2443096620191,32.846983,-117.244310,Pothole
2570,92067,Assigned,In process,0,0,2016-07-10T17:08:00,NaN,1,0,Pothole,32.758429-117.113232,32.758429,-117.113232,Pothole
2571,92995,Assigned,In process,0,0,2016-07-05T14:01:00,NaN,1,0,Pothole,32.901876-117.158525,32.901876,-117.158525,Pothole
2572,94233,Assigned,In process,0,1,2016-06-27T12:37:00,NaN,1,0,Pothole,32.92606398398056-117.25647124565836,32.926064,-117.256471,Pothole
2573,100727,Assigned,In process,0,0,2016-05-22T10:33:00,NaN,1,0,Pothole,00,NaN,NaN,Pothole

In [23]:
def haversine_np(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)

    All args must be of equal length.    

    """
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2

    return np.arcsin(np.sqrt(a))

In [24]:
#start of death
busResults = np.zeros((len(bus_stops),len(open_pot)))
meterResults = np.zeros((len(bus_stops),len(open_pot)))

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [29]:
for i in bus_stops.index:
    for j in open_pot.index:
        bus_stop = bus_stops.iloc[i]
        open_pott = open_pot.iloc[j]
        busResults[i][j] = haversine_np(bus_stop['LONGITUDE'], bus_stop['LATITUDE'], open_pott['long'], open_pott['lat'])
np.save('distances.npy',busResults)

In [30]:
for i in merged_id.index:
    for j in open_pot.index:
        meter = merged_id.iloc[i]
        open_pott = open_pot.iloc[j]
        meterResults[i][j] = haversine_np(meter['longitude'], meter['latitude'], open_pott['long'], open_pott['lat'])
results
np.save('distances.npy',meterResults)